### ISSUE TITLE
PieChart 스토리 작성

### ISSUE THREAD

**Issue by xhseb** [innovationacademy-kr/42dashboard#108]
Kilee님에게 Storybook에 대한 설명을 들은 후 구현해보았습니다.
[간단한 컴포넌트 만들기](https://storybook.js.org/tutorials/intro-to-storybook/react/ko/simple-component/)를 PieChart에 적용시켜보았습니다.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/60543629/176423912-6fadcf01-4473-4109-ae63-b3138bcef811.png">

**Comment by Likilee** [comment]
엄청 빠르게 적용하셨네용 :)
가이드 문서에 타입스크립트 버전 예시가 부족한데, 찾아보니 저희 소스코드 client/src/stories에 보면 예시 스토리들이 타입스크립트로 작성되어 있어 참고하시면 좋을거 같아요 😀
