### ISSUE TITLE
jest로 테스트 자동화

### ISSUE THREAD

**Issue by 20151883** [innovationacademy-kr/42dashboard#131]
jest를 통해 테스트 자동화 기능을 추가해 볼 계획입니다.

**Comment by 20151883** [comment]
[nestjs/in-memoryDB 패키지](https://www.npmjs.com/package/@nestjs-addons/in-memory-db)
테스트할때 repository 사용을 무조건 할텐데, 테스트용임에도 postgresql을 쓰는건 낭비라고 생각.
그래서 in memory DB를 사용. (H2를 사용하려다가 nestjs를 위한 in memory DB 모듈이 있어서 이것을 사용)

**Comment by Likilee** [comment]
제스트 사용 너무 좋네요 한번 가르쳐주시면 좋겠어요 ㅎㅎ

**Comment by 20151883** [comment]
https://stackoverflow.com/questions/55717089/test-nestjs-service-against-actual-database
https://ssowonny.medium.com/%EC%84%A4%EB%A7%88-%EC%95%84%EC%A7%81%EB%8F%84-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%9E%91%EC%84%B1-%EC%95%88-%ED%95%98%EC%8B%9C%EB%82%98%EC%9A%94-b54ec61ef91a
yarn add sqlite3 --save
https://dzone.com/articles/7-popular-unit-test-naming
https://eddie-sunny.tistory.com/14(vscode snippet)
