### ISSUE TITLE
api 명세 및 가이드 작성

### ISSUE THREAD

**Issue by jungmyeong96** [innovationacademy-kr/42dashboard#154]
https://canyon-coaster-6f1.notion.site/1cc6933784134ffbacfbd3afef915eaf

**Comment by hunjin-choi** [comment]
https://canyon-coaster-6f1.notion.site/1cc6933784134ffbacfbd3afef915eaf
위 노션 주소에 명세서 작성하여 프론트엔드팀에 공유 완료
